### ISSUE TITLE
Closing a playing video in modal causes site not to continue loading.

### ISSUE THREAD

**Issue by Pletron** [idleberg/Bootstrap-Listr#181]
Hi,

I'm having troubles closing modals while a video is playing. What happens is that if I try to go to any other link on the site it gets stuck in loading and nothing happens.

/Philip

**Comment by Pletron** [comment]
I believe it has something to do with that the stream playing the video is not closed properly.

**Comment by idleberg** [comment]
I could reproduce this on my test-server and believe this is caused by the fairly new `readfile_chunked()` (b498e4be3f5d076f9ae102e2916c8c3d9f150c74) function. As of [2.0.6](https://github.com/idleberg/Bootstrap-Listr/releases/tag/2.0.6) the user can specify whether to read files in chunks (disabled by default). Please give it a try!

**Comment by idleberg** [comment]
Can this issue be closed?
