### ISSUE TITLE
.swf Video Support

### ISSUE THREAD

**Issue by Bonfire** [idleberg/Bootstrap-Listr#229]
Currently, the in-built viewer can play the audio from SWF files, but cannot show the video. Are there any plans to add .swf file support for the in-built viewer? Thanks for your time.

**Comment by idleberg** [comment]
I wonder if all it takes is adding an additional JavaScript library, which you can already do specifying `append_js` in `config.json`. Otherwise I don't have explicit plans to support that, though in longterm (v3.0), I would like to keep the view more flexible and maybe adding a plugin architecture.

**Comment by Bonfire** [comment]
Thanks for the quick response, I'll be sure to look into adding a library to my append_js.

**Comment by idleberg** [comment]
Let me know if it worked, we could post this as an example

**Comment by idleberg** [comment]
If think if you're adding [swfobject.js](http://blog.deconcept.com/swfobject/), you could append a second script that fires on `.embed-responsive-item` — `append_js` is an array!
