### ISSUE TITLE
How to open files in another tab.

### ISSUE THREAD

**Issue by smartpapers** [idleberg/Bootstrap-Listr#342]
Hi @idleberg 
I wanted to know if there is anyway I can make the PDF files open in another tab.
For example I browse through the lister from folder to folders etc.
Then whenever I open a PDF file or any sort of "File" not folder, It should open that thing in a new tab.

Is it possible? 
Please let me know.
Thanks

**Comment by idleberg** [comment]
At first I wasn't sure what you're asking for before noticing that, with `enable_viewer` set to `true`, the default shortcut to open in a new tab (e.g. <kbd>Cmd</kbd> + mouse-click on macOS does not work). However, you can still select ”Open in New Tab” from the context menu or using the middle mouse-button (not sure if that's a default action).

With the viewer disabled, <kbd>Cmd</kbd> + mouse-click works fine. I'll have to look into the issue, why it's not working when the viewer is enabled.

**Comment by smartpapers** [comment]
No can we make it like we simply click on the document, Or tap as in mobile browsers and it opens the links in a new window?

**Comment by idleberg** [comment]
I'm opposed to the target attribute for reasons described in [this article](https://css-tricks.com/use-target_blank/). As I said before, there are better ways to open files in new tabs. However, I'm going to leave this issue open and consider making Listr v3 more flexible, so that it's easier to customize it that way.

**Comment by smartpapers** [comment]
So for now there is no solution to it?
